### ISSUE TITLE
Erro quando o usuário não tem atividade cadastrada

### ISSUE THREAD

**Issue by phborba** [1cgeo/Ferramentas_Producao#1]
Erro no QGIS 3.4 quando o usuário não tem mais atividade cadastrada.

Traceback (most recent call last):
  File "/home/tenborba/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/managerSAP.py", line 59, in login
    sucess = self.init_works(server, user, password, token)
  File "/home/tenborba/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/managerSAP.py", line 112, in init_works
    token
  File "/home/tenborba/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/managerSAP.py", line 79, in update_sap_data
    works = data['dados']['atividade']['nome']
KeyError: 'dados'

**Comment by jossanCosta** [comment]
resolvido no commit 3023a0da52e187c280f98c163426e3b0880433a1
