### ISSUE TITLE
Erro ao pegar trabalho cadastrado

### ISSUE THREAD

**Issue by phborba** [1cgeo/Ferramentas_Producao#2]
Estou tentando testar o Ferrametas de Produção no QGIS 3.4 e fiz um teste semelhante no qgis 2.18 (que funcionou), porém ao tentar requisitar a próxima atividade, o seguinte erro foi levantado:

psycopg2.ProgrammingError: column "mi" does not exist LINE 1: SELECT mi FROM edgv.aux_moldura_a;               ^ 
Traceback (most recent call last):
  File "/home/tenborba/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Tools/tools.py", line 52, in load_frame
    self.tool_selected.get_frame()
  File "/home/tenborba/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Tools/LoadData/loadData.py", line 43, in get_frame
    self.update_frame()
  File "/home/tenborba/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Tools/LoadData/loadData.py", line 120, in update_frame
    db_json = self.postgresql.load_db_json(db_name)
  File "/home/tenborba/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/../Database/postgresql.py", line 197, in load_db_json
    db_json = self.get_db_json()
  File "/home/tenborba/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/../Database/postgresql.py", line 184, in get_db_json
    u"db_workspaces_name" : self.get_workspaces_name(u"aux_moldura_a"),
  File "/home/tenborba/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/../Database/postgresql.py", line 63, in get_workspaces_name
    result = self.run_sql(sql)
  File "/home/tenborba/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/../Database/postgresql.py", line 291, in run_sql
    self.pg_cursor.execute(sql)
psycopg2.ProgrammingError: column "mi" does not exist
LINE 1: SELECT mi FROM edgv.aux_moldura_a;
               ^

**Comment by jossanCosta** [comment]
resolvido no commit  3023a0da52e187c280f98c163426e3b0880433a1
